### PR TITLE
5 corrections to MW dictionary

### PR DESCRIPTION
**Pull request by aumsanskrit**
Update L id 50272 in MW dictionary
Update L id 129737 in MW dictionary
Update L id 247531 in MW dictionary
Update L id 247532 in MW dictionary
Update L id 247639 in MW dictionary

*Note on ID 129737 – Here is something to look into. The printed text clearly reads "pnā". However, now look up the word "supta" (a mfn.). Monier Williams clearly reports as follows, "(fr. su + ptā) having beautiful braids of hair." He is quoting his own source (i.e. ptā) which appears to be incorrect according to the printed text of ID 129737.

### CODE REVIEW

**Comment by drdhaval2785** [comment]
I am not very convinced regarding "pnA" and "ptA".

**Comment by Andhrabharati** [comment]
It is just a print change mentioned in the MW itself. Originally picked up pnA from PWG, pwk and the amendment ptA was taken from pwkvn (indirectly mentioned!!).

The need for appropraitely marking the author's own amendments (if and when integrated into the main text) was discussed long back, and you had also pointed it out quire recently.

I think, now it is high time to implement the same.

Pl. see how it was done in GRA (about 6 months back), which is sufficient for all purposes.

**Comment by Andhrabharati** [comment]
PWG4-896
image

(& pwk 4-126b)
image


showed up in MW as 
MW652-2
image



And then, pwk7-359d (pwkvn)
image

showed up in MW as
image
with the `<info n="rev" pc="1330,2"/>` tag in mw.txt!!

**Comment by aumsanskrit** [comment]
Thank you Andhrabharati for making this clear.

**Pull request merged**
